# Site
repository: feluelle/feluelle.github.io
favicon: images/favicon.ico

# Personal info
name: Felix Uellendall
title: Data Engineer ğŸ‘¨ğŸ¼â€ğŸ’» @traderepublic | Open Sourcerer ğŸ§™ @â¤ï¸ | Committer @apache Airflow ğŸª¶
email: feluelle@pm.me
website: feluelle.github.io

# Social links
# twitter_username:
github_username: feluelle
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: feluelle
xing_username: Felix_Uellendall
# pinterest_username:
# youtube_username: globalmtb
# googleplus_username: +jekyll
# additional_links:
#   - title: felix.uellendall
#     url: https://medium.com/@felix.uellendall
#     icon: fa-medium

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  Hi ğŸ‘‹ğŸ¼, my name is Felix Uellendall. I am a Data Engineer ğŸ§‘ğŸ¼â€ğŸ’» working in the data infrastructure team for a bank ğŸ¦ in
  Berlin, Germany. I joined the Apache Software Foundation in September 2019. Since then I am also an Apache
  Airflow Committer.

  ### Tools & Services

  ![ApacheAirflow](https://img.shields.io/badge/ApacheAirflow-017CEE?style=for-the-badge&logo=ApacheAirflow&logoColor=white)![Docker](https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=Docker&logoColor=white)![Python](https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=Python&logoColor=white)![AmazonAWS](https://img.shields.io/badge/AmazonAWS-232F3E?style=for-the-badge&logo=AmazonAWS&logoColor=white)![Snowflake](https://img.shields.io/badge/Snowflake-29B5E8?style=for-the-badge&logo=Snowflake&logoColor=white)![dbt](https://img.shields.io/badge/dbt-FF694B?style=for-the-badge&logo=dbt&logoColor=white)![PostgreSQL](https://img.shields.io/badge/PostgreSQL-4169E1?style=for-the-badge&logo=PostgreSQL&logoColor=white)![Terraform](https://img.shields.io/badge/Terraform-7B42BC?style=for-the-badge&logo=Terraform&logoColor=white)![Kubernetes](https://img.shields.io/badge/Kubernetes-326CE5?style=for-the-badge&logo=Kubernetes&logoColor=white)

  _Sorted by Expertise_

  _Badges created via [auto-markdown-badges](https://github.com/feluelle/auto-markdown-badges)_

  ### Industrial Knowledge

  `Data Engineering` `Software Engineering` `Unit Testing` `Orchestration` `Batch Processing` `Data Lake` `Data Ingestion` `CI/CD` `Data Infrastructure` `Distributed Systems` `ETL/ELT` `Monitoring` `Alerting` `Data Observability` `Stream Processing`

  _Sorted by Expertise_

  ### Languages

  * German ğŸ‡©ğŸ‡ª (Native speaker)
  * English ğŸ‡¬ğŸ‡§ (Upper-intermediate)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: |
  I love creating things, solving puzzles, thinking about code and improving challenging problems.
  Open Source is what I like doing the most. I enjoy working in the community and sharing my knowledge with each other.

  I also fell in love with the nature and the silence being out there.
  I like hiking, playing the piano and I am fascinated by the universe.

# Footer
footer_show_references: true

darkmode: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
