# Site
repository: feluelle/feluelle.github.io
favicon: images/favicon.ico

# Personal info
name: Felix Uellendall
title: Data Engineer, Open Source Enthusiast and Apache Airflow Committer 
email: feluelle@pm.me
website: feluelle.github.io

# Social links
# twitter_username: 
github_username: feluelle
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: feluelle
xing_username: Felix_Uellendall
# pinterest_username: 
# youtube_username: globalmtb
# googleplus_username: +jekyll
# additional_links:
#   - title: felix.uellendall
#     url: https://medium.com/@felix.uellendall
#     icon: fa-medium

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  Hi ğŸ‘‹ğŸ¼, my name is Felix Uellendall. I am a Data Engineer ğŸ§‘ğŸ¼â€ğŸ’» working in a data team for a bank ğŸ¦ in 
  Berlin, Germany. I joined the Apache Software Foundation in September 2019. Since then I am also an Apache 
  Airflow Committer.

  **Technical Skills ğŸ’»**

  I am most skilled in:

  * Apache Airflow
  * Docker
  * Python
  * Terraform
  * Unit Testing

  I have experience in:

  AWS, Bash, CI/CD, dbt, Distributed Systems, ETL/ELT, Git, great_expectations, Kubernetes, PostgreSQL,
  REST, Snowflake, Software Design, Software Development, System Testing, Test Driven Development

  **Languages ğŸ’¬**

  German (Native speaker) and English (Upper-intermediate)

# Are you interested in what I am currently [writing](https://medium.com/@felix.uellendall) about? 
# Or would you like to [connect](https://www.linkedin.com/in/feluelle/)?

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: |
  I love creating things, solving puzzles, thinking about code and improving challenging problems.
  Open Source is what I like doing the most. I enjoy working in the community and sharing my knowledge with each other.

  I also fell in love with the nature and the silence being out there.
  I like hiking, playing the piano and I am fascinated by the universe.

# Footer
footer_show_references: true

darkmode: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
